[platformio]
default_envs = waveshare-esp32-release

[env:waveshare-esp32-base]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.38-1/platform-espressif32.zip
board = waveshare_esp32_touch_lcd_35
framework = arduino

monitor_speed = 115200
upload_speed = 460800
monitor_filters = esp32_exception_decoder

board_build.partitions = partitions_16mb.csv

build_flags =
    -D LV_CONF_INCLUDE_SIMPLE
    -I include
    -I src

lib_deps =
    lvgl/lvgl@8.4.0
    https://github.com/moononournation/Arduino_GFX.git#v1.6.5
    lewisxhe/SensorLib@0.3.1
    robtillaart/TCA9554@0.1.2
    jgromes/RadioLib@7.7.1
    mikalhart/TinyGPSPlus@^1.1.0
    lewisxhe/XPowersLib@0.3.3

[env:waveshare-esp32-release]
extends = env:waveshare-esp32-base
build_type = release
build_flags =
    ${env:waveshare-esp32-base.build_flags}
    -D APP_LOG_LEVEL=2

[env:waveshare-esp32-debug]
extends = env:waveshare-esp32-base
build_type = debug
build_flags =
    ${env:waveshare-esp32-base.build_flags}
    -D APP_LOG_LEVEL=4
    -D CORE_DEBUG_LEVEL=3

[env:native]
platform = native
test_framework = unity
test_filter = test_aprs_core
build_flags =
    -std=gnu++17
