#include "ui/screens/weather_detail_screen.h"
#include <cstdio>
#include <lvgl.h>
#include "services/geo_utils.h"
#include "ui/aprs_icons.h"
#include "ui/ui_components.h"
namespace Ui { namespace WeatherDetailScreen { namespace {
lv_obj_t *titleLabel=nullptr,*mainLabel=nullptr,*extraLabel=nullptr,*packetLabel=nullptr,*iconObject=nullptr;
void ageText(char* out,std::size_t cap,std::uint32_t ms){auto s=ms/1000U;if(s<60)std::snprintf(out,cap,"%lu s",(unsigned long)s);else if(s<3600)std::snprintf(out,cap,"%lu min",(unsigned long)(s/60));else std::snprintf(out,cap,"%lu h %lu min",(unsigned long)(s/3600),(unsigned long)((s/60)%60));}
}
void create(){resetScreen();createHeader("Detail meteostanice");lv_obj_t* card=lv_obj_create(lv_scr_act());lv_obj_set_size(card,450,194);lv_obj_align(card,LV_ALIGN_TOP_MID,0,54);lv_obj_set_style_bg_color(card,lv_color_hex(0x17243A),0);lv_obj_set_style_border_color(card,lv_color_hex(0x31425F),0);lv_obj_set_style_border_width(card,1,0);lv_obj_set_style_radius(card,12,0);lv_obj_set_style_pad_all(card,10,0);lv_obj_clear_flag(card,LV_OBJ_FLAG_SCROLLABLE);
titleLabel=lv_label_create(card);lv_obj_set_width(titleLabel,360);lv_obj_set_style_text_font(titleLabel,&lv_font_montserrat_22,0);lv_obj_set_style_text_color(titleLabel,lv_color_hex(0xF4F7FF),0);lv_obj_align(titleLabel,LV_ALIGN_TOP_LEFT,0,0);
mainLabel=lv_label_create(card);lv_obj_set_width(mainLabel,425);lv_label_set_long_mode(mainLabel,LV_LABEL_LONG_WRAP);lv_obj_set_style_text_font(mainLabel,&lv_font_montserrat_16,0);lv_obj_set_style_text_color(mainLabel,lv_color_hex(0xBDCAE0),0);lv_obj_align(mainLabel,LV_ALIGN_TOP_LEFT,0,34);
extraLabel=lv_label_create(card);lv_obj_set_width(extraLabel,425);lv_label_set_long_mode(extraLabel,LV_LABEL_LONG_WRAP);lv_obj_set_style_text_font(extraLabel,&lv_font_montserrat_14,0);lv_obj_set_style_text_color(extraLabel,lv_color_hex(0x56C7FF),0);lv_obj_align(extraLabel,LV_ALIGN_TOP_LEFT,0,100);
packetLabel=lv_label_create(card);lv_obj_set_width(packetLabel,425);lv_obj_set_height(packetLabel,42);lv_label_set_long_mode(packetLabel,LV_LABEL_LONG_WRAP);lv_obj_set_style_text_font(packetLabel,&lv_font_montserrat_14,0);lv_obj_set_style_text_color(packetLabel,lv_color_hex(0xFFFFFF),0);lv_obj_align(packetLabel,LV_ALIGN_TOP_LEFT,0,136);}
void update(const Services::WeatherStore::WeatherStation& s,const Services::PositionReference& ref,std::uint32_t now){if(!titleLabel)return;lv_label_set_text(titleLabel,s.entityName[0]?s.entityName:s.callsign);if(!iconObject){iconObject=AprsIcons::create(lv_obj_get_parent(titleLabel),s.symbol[0],s.symbol[1],s.hasPosition);lv_obj_align(iconObject,LV_ALIGN_TOP_RIGHT,-2,4);}char t[20]="--",h[20]="--",p[24]="--";if(s.hasTemperature)std::snprintf(t,sizeof(t),"%.1f C",(double)s.temperatureC);if(s.hasHumidity)std::snprintf(h,sizeof(h),"%.0f %%",(double)s.humidityPercent);if(s.hasPressure)std::snprintf(p,sizeof(p),"%.1f hPa",(double)s.pressureHpa);lv_label_set_text_fmt(mainLabel,"Teplota %s | vlhkost %s\nTlak %s\nVitr %.0f deg / %.1f km/h | naraz %.1f km/h",t,h,p,(double)s.windDirectionDegrees,(double)s.windSpeedKmh,(double)s.windGustKmh);
char age[24];ageText(age,sizeof(age),now-s.lastHeardMs);char rel[80]="vzdalenost --";if(s.hasPosition&&ref.valid){auto r=Services::calculateDistanceBearing(ref.latitude,ref.longitude,s.latitude,s.longitude);if(r.valid)std::snprintf(rel,sizeof(rel),"%.2f km | %03.0f deg %s",r.distanceKm,r.bearingDegrees,Services::cardinalDirection(r.bearingDegrees));}lv_label_set_text_fmt(extraLabel,"Dest 1h %.1f | 24h %.1f | dnes %.1f mm | solar %.0f W/m2\n%s | RSSI %.1f | SNR %.1f | stari %s",(double)s.rainLastHourMm,(double)s.rainLast24HoursMm,(double)s.rainTodayMm,(double)s.solarRadiationWm2,rel,(double)s.lastRssiDbm,(double)s.lastSnrDb,age);lv_label_set_text(packetLabel,s.lastFrame[0]?s.lastFrame:"TNC2 ramec neni ulozen.");}
} }
